"""empty message

Revision ID: 74d4e49dec98
Revises: 
Create Date: 2019-09-04 18:18:09.517206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d4e49dec98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewers',
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_name', sa.String(length=50), nullable=False),
    sa.Column('interviewer_email', sa.String(length=50), nullable=False),
    sa.Column('interviewer_designation', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('interviewer_id')
    )
    op.create_table('interviewertimeslots',
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_start_time', sa.String(), nullable=False),
    sa.Column('interviewer_end_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewers.interviewer_id'], ),
    sa.PrimaryKeyConstraint('time_id')
    )
    op.drop_table('Interviewertimeslots')
    op.drop_table('Jobid')
    op.drop_table('Interviewers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Interviewers',
    sa.Column('interviewer_id', sa.INTEGER(), nullable=False),
    sa.Column('interviewer_name', sa.NUMERIC(precision=50), nullable=True),
    sa.Column('interviewer_email', sa.NUMERIC(precision=50), nullable=True),
    sa.Column('interviewer_designation', sa.NUMERIC(precision=50), nullable=True),
    sa.ForeignKeyConstraint(['interviewer_designation'], ['Jobid.job_role'], ),
    sa.PrimaryKeyConstraint('interviewer_id')
    )
    op.create_table('Jobid',
    sa.Column('job_role', sa.NUMERIC(precision=50), nullable=True)
    )
    op.create_table('Interviewertimeslots',
    sa.Column('time_id', sa.INTEGER(), nullable=False),
    sa.Column('interviewer_id', sa.INTEGER(), nullable=False),
    sa.Column('interviewer_start_time', sa.NUMERIC(), nullable=True),
    sa.Column('interviewer_end_time', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['interviewer_id'], ['Interviewers.interviewer_id'], ),
    sa.PrimaryKeyConstraint('time_id')
    )
    op.drop_table('interviewertimeslots')
    op.drop_table('interviewers')
    # ### end Alembic commands ###
